### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by blahutka** [barriehadfield/heart-cards#3]
Hi @barriehadfield, when I try to tun in production
1. `RAILS_ENV=production rails assets:precompile`
2. `RAILS_ENV=production rails s` 

The compiled `application.js` files includes wrong code `<div data-react-class="React.TopLevelRailsComponent"`

Do you have any idea what's wrong?

**Comment by barriehadfield** [comment]
Hi

I don't know what it can be but will have a look this weekend.

Thanks for trying!

**Comment by barriehadfield** [comment]
Hi @blahutka I have had a look at this, but I am not getting as fart as you are. The project at the moment is configured to build for Heroku production, so I am falling over getting it built for a loca production instance (at the moment the assets are not being found). Could you push your version and then I can look at the specific problem you are seeing? I am suspecting it has something to do with pre-rendering..

**Comment by blahutka** [comment]
Ok, @barriehadfield I tried on Heroku and it's working. That is fine with me. 
Thank you for your time.

**Comment by barriehadfield** [comment]
Pleasure! Let me know if you do find out what it was, please.
